### ISSUE TITLE
Can't build on clean machine due to jcenter redirect

### ISSUE THREAD

**Issue by scf37** [bailuk/java-gtk#21]
Fix is to add pluginManagement to `settings.gradle.kts`

```
pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
```

See https://github.com/gradle/gradle/issues/15406

**Comment by bailuk** [comment]
I cannot reproduce this with current master (release 0.40) and gradle wrapper (version 8.1).
Does this problem still persist? If so, how can it be reproduced?

**Comment by scf37** [comment]
Can't reproduce it as well, can be closed I guess
