### ISSUE TITLE
macos startup of example causes exception 

### ISSUE THREAD

**Issue by dadkins789** [bailuk/java-gtk#23]
On Macos 10, 12 and 13 using either java 17 or java 19 with homebrew gtk 4.10.4 on a paired down example from v0.4.0:

[results.txt](https://github.com/bailuk/java-gtk/files/11690029/results.txt)

2023-06-08 10:06:16.095 java[7961:51584] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007ff80ec2a773 __exceptionPreprocess + 242
        1   libobjc.A.dylib                     0x00007ff80e98abc3 objc_exception_throw + 48
        2   AppKit                              0x00007ff8115e72d1 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 4633
        3   libgtk-4.1.dylib                    0x00000001094ceb43 poll_func + 179
        4   libglib-2.0.0.dylib                 0x0000000102b4901b g_main_context_iterate + 349
        5   libglib-2.0.0.dylib                 0x0000000102b490cc g_main_context_iteration + 55
        6   libgio-2.0.0.dylib                  0x0000000108d74ca3 g_application_run + 521
        7   jna16203219141762940508.tmp         0x00000001029eb17a ffi_prep_go_closure + 1370
        8   ???                                 0x0000700001efc688 0x0 + 123145334802056
)
libc++abi: terminating with uncaught exception of type NSException

Runs fine on Fedora 38 with openjdk 17.

**Comment by bailuk** [comment]
Looks like libgtk calls the macos specific function `poll_func` from a thread other than the main thread.

https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/macos/gdkmacoseventsource.c

On the java side everything should be in the main thread.

- Does this also happen when running this example: https://github.com/bailuk/java-gtk/blob/main/examples/src/main/java/examples/HelloWorld.java ?

- Are other (non-java) gtk applications running on your Macos 10 installation?

**Comment by dadkins789** [comment]
I get the same results with the helloword. I've included the source with gradle build. I've got gtk4 running fine in rust using gtk-rs.. Gtk3 running with rust and c++ and haskell (ghc 9.2.7). I've run this on MacOS 10, MacOS 12, and MacOS 13 (M1). On linux its Fedora latest and raspberry pi in those languages, all native compiles.
[hello.tar.gz](https://github.com/bailuk/java-gtk/files/11709022/hello.tar.gz)

**Comment by bailuk** [comment]
This statement prints out thread identification to stdout:
```java
System.out.println(Thread.currentThread().toString());
```
You can add this to the main function to see in what threads the application starts.

This post https://stackoverflow.com/questions/34594946/running-swt-application-on-mac-throws-illegal-thread-access indicates that on macos JVM does not start with the main thread. Maybe it works with `-XstartOnFirstThread` option.

**Comment by dadkins789** [comment]
Using  -XstartOnFirstThread seems to fix the problem. In both cases, with and without the startOnFirstThread option, the println yeilds Thread[main,5,main]. The println is right before the app.run() and also in the top of the onActivate() callback.

Interestingly, I haven't had this problem with Clojure SWT apps. 

It now runs on all my MacOS platforms including the 13.4 M1 system.
[hello.tar.gz](https://github.com/bailuk/java-gtk/files/11712634/hello.tar.gz)

I wonder why startOnMainThread isn't always the default and what is happening here that triggers other behavior.

Thanks for the help.
