### ISSUE TITLE
cairo-custom.gir

### ISSUE THREAD

**Issue by dadkins789** [bailuk/java-gtk#24]
I've noticed that two methods I use in gtk.cairo.Context are not present and have added them. They are really needed to easily use showText. Was there a reason they were not included?
 
[select_font.txt](https://github.com/bailuk/java-gtk/files/11907805/select_font.txt)

**Comment by dadkins789** [comment]
BTW,  Here's the whole cairo-custom.gir with its name changed to cairo-custom.git
[cairo-custom.txt](https://github.com/bailuk/java-gtk/files/11907882/cairo-custom.txt)

**Comment by bailuk** [comment]
Added to stage branch.
See comment: https://github.com/bailuk/java-gtk/discussions/12
