### ISSUE TITLE
Broken button text in FileChooserDialog

### ISSUE THREAD

**Issue by MasFlam** [bailuk/java-gtk#5]
This code sample:
```java
public static void main(String[] args) {
    var app = new Application(new Str("example.javagtk.FileChooserDialog"), ApplicationFlags.FLAGS_NONE);
    app.onActivate(() -> {
        var appWin = new ApplicationWindow(app);
        var fcd = new FileChooserDialog(new Str("Open savefile"), appWin, FileChooserAction.OPEN, new Str("Open"));
        appWin.show();
        fcd.show();
    });
    System.exit(app.run(args.length, new Strs(args)));
}
```
Produces a GTK file chooser dialog with broken button text, seen below:
![image](https://user-images.githubusercontent.com/19764975/159134071-0d355ffa-baf6-4aa4-983b-5f3df02d062f.png)
The broken text seems to be read from an incorrect place in memory by GTK. Pressing any of the buttons in my case also results in a segfault.
This happens on a Debian Unstable machine, using the GTK4 library from apt, and OpenJDK 17 installed through sdkman.

**Comment by bailuk** [comment]
The constructor FileChooserDialog(...) calls [gtk_dialog_new_with_buttons](https://docs.gtk.org/gtk4/ctor.FileChooserDialog.new.html), this function expect a list of arguments (varargs) with `null` as the last argument. 

java-gtk does not yet support varargs.

A workaround is to add buttons separately:

```java
public static void main (String[] args)  {
    var app = new Application(new Str("example.javagtk.FileChooserDialog"), ApplicationFlags.FLAGS_NONE);
    app.onActivate(() -> {
        var appWin = new ApplicationWindow(app);
        var fcd = new FileChooserDialog(new Str("Open savefile"), appWin, FileChooserAction.OPEN, null);
        fcd.addButton(new Str("Open"), 1);
        fcd.addButton(new Str("Button 2"), 2);
        appWin.show();
        fcd.show();
    });
    System.exit(app.run(args.length, new Strs(args)));
}
```


Possible Fixes:
- Implement varargs. This should be possible with JNA. The last parameter must still be `null`.
- Do not support this constructor. => There seems to be no alternative for this constructor

**Comment by MasFlam** [comment]
Oh, okay. Yeah, I remember varargs being a problem in Julia's CCall too.
As for possible fixes, you could also maybe have the Java constructor take a vararg of some structure containing a `Str` and an `int`, even if it's not as elegant in java. Or you could make the constructor not take any button info and explain it in javadoc, which would be simpler.
Thanks! :)

**Comment by MasFlam** [comment]
Also I have a question: do I have to somehow free the `GFile` handle returned by `FileChooser#getFile()` myself, or does java-gtk or JNA do it for me? And does this apply to other gobjects like `Str` etc., where I don't give ownership of them to a GTK widget?

**Comment by bailuk** [comment]
Yes you probably have to call `new ch.bailu.gtk.gobject.Object(file.cast()).unref();` in this case. Every subclass of `ch.bailu.gtk.gobject.Object` has of course a `unref()` member function.

Wrapper types such as `Str` have a `destroy()` function.

Callbacks and signals are freed by calling `ch.bailu.gtk.Refs.remove(aLambda);` (They are locked, so GC does not remove them too early)
