### ISSUE TITLE
does this work on windows?

### ISSUE THREAD

**Issue by me6262** [bailuk/java-gtk#9]
i'd like to make a cross-platform app using this and it would be very nice to know before i start if this can run on windows. as i dont have a windows installation right now, i have no way to verify

**Comment by me6262** [comment]
i know that jna works and that gtk4 works, but i have no idea if there is some form of compatibility issue with the way you generate the bindings

**Comment by bailuk** [comment]
I never tried to run `java-gtk` on Windows. I also don't know anything about the differences between Unix and Windows gtk.

This is how libraries are getting loaded from the generated code:

```java
    static Instance INST() {
        if (INSTANCE == null) {
            INSTANCE = com.sun.jna.Native.load("glib-2.0", Instance.class);
        }
        return INSTANCE;
    }
```

Assumed the naming of the libraries are the same on Windows and the libraries are API compatible, I would give it a try.

If something does not work, feel free to report it here.

**Comment by me6262** [comment]
is there a way to add gtk4 or adwaita to the build.gradle so it grabs them on first build?

**Comment by bailuk** [comment]
Libraries are loaded durring runtime when needed. They just need to be installed and in the PATH. Most likely you need to install the libraries with msys as described here https://www.gtk.org/docs/installations/windows/

**Comment by bailuk** [comment]
I've manged to run the demo app in Windows, but not without changes in the source code.

If you want to try this out, you need to check out the 'windows' branch and build and configure everything as described in [windows.md](https://github.com/bailuk/java-gtk/blob/windows/doc/windows.md). 

Its not yet working in the official branch yet because all library names are different.

Also note that `Adwaita` support is still limited because `java-gtk` does not yet provide an easy way for sub classing.

**Comment by bailuk** [comment]
![adwaita-windows](https://user-images.githubusercontent.com/16067257/222904204-34687c95-f21c-4928-86ab-6aab5b477c0b.png)

And that is how it looks like

**Comment by me6262** [comment]
thats awesome! ill check it out soon.

**Comment by me6262** [comment]
how would i add this branch as a gradle dependency? I'm pretty new to gradle in general

**Comment by me6262** [comment]
> Its not yet working in the official branch because all library names are different.

could you use `System.getProperty("os.name")` and if its windows look for one library and if other, look for the linux libraries?

**Comment by me6262** [comment]
also, I am trying to use a FileChooserNative, but I cannot seem to figure out how to access any of the methods that the gtk docs say that it implements from the FileChooser interface. Is this a thing with me not knowing how it works? or is it an issue with the bindings?

**Comment by bailuk** [comment]
- Dynamic file loader is now in stage: https://github.com/bailuk/java-gtk/tree/stage 
- See https://github.com/bailuk/java-gtk/blob/stage/doc/windows.md
- All changes in "stage" until next release

**Comment by bailuk** [comment]
Interface functions can be accessed by casting, that would be something like this:
```Java
var fileChoserNative = new FileChooserNative(fileCooser.cast());
```
Careful: This will crash if the classes do not share the same interface

**Comment by me6262** [comment]
nevermind, with some tinkering it works now.

**Comment by me6262** [comment]
does this mean a release with windows support is coming in the very near future?

**Comment by bailuk** [comment]
- Windows support is now in the stage branch
- Everything that is in stage will be in the next release
- In the meantime you can integrate stage into your project, for testing and developing: https://jitpack.io/#bailuk/java-gtk/stage-SNAPSHOT
- I've also activated GitHub discussions for this  repo: https://github.com/bailuk/java-gtk/discussions for questions
